#!/usr/bin/env python3
"""Generate AGENTS.md anti-idle directives for Codex CLI.

Codex CLI reads ``AGENTS.md`` (and ``AGENTS.override.md``) as its
instruction file.  Since Codex has no runtime hooks, polling behavior
must be encoded as strong instruction-level directives.

This module generates role-specific AGENTS.md content that keeps
Codex agents working continuously, mirroring the anti-idle guarantees
that Claude/Gemini achieve via Stop hook exit-code-2 blocking.

Usage:
    from vibecodehpc.hooks.templates.codex.agents_md import generate_agents_md

    content = generate_agents_md(role="PG", agent_id="PG1.1")
    Path("AGENTS.md").write_text(content)
"""

from typing import Optional


# ---------------------------------------------------------------------------
# Role-specific task lists and priorities
# ---------------------------------------------------------------------------

_ROLE_TASKS = {
    "PM": {
        "description": "Project Manager — Overall progress monitoring, directive distribution, SOTA/Budget management",
        "polling_tasks": [
            "Check each agent's ChangeLog.md and assess progress",
            "Check agent status via Agent-shared/agent_and_pane_id_table.jsonl",
            "Check budget consumption and issue warnings as needed",
            "Check for SOTA updates and notify all agents of new records",
            "Update ToDoList.md and reassign priority tasks",
            "Detect stopped or abnormal agents and issue recovery instructions",
            "Send directives to agents via agent_send.sh",
        ],
        "check_files": [
            "Agent-shared/directory_pane_map.md",
            "Agent-shared/budget/snapshots/latest.json",
            "sota_project.txt",
        ],
    },
    "SE": {
        "description": "System Engineer — Compilation, job management, result analysis",
        "polling_tasks": [
            "Compile code generated by PG agents",
            "Provide feedback to PG on compilation errors",
            "Submit jobs and monitor results",
            "Record performance results in ChangeLog.md",
            "Perform SOTA determination and report updates",
            "Report progress to PM via agent_send.sh",
        ],
        "check_files": [
            "ChangeLog.md",
            "Agent-shared/skills/changelog-format/references/changelog_api.md",
        ],
    },
    "PG": {
        "description": "Programmer — Code generation, optimization, version management",
        "polling_tasks": [
            "Check the latest ChangeLog.md entry to understand previous results",
            "Select the next optimization task from ToDoList.md",
            "Check for directive messages from SE or PM",
            "Modify and optimize code, generate new versions",
            "Add new entries to ChangeLog.md",
            "Send compile/test requests to SE via agent_send.sh",
        ],
        "check_files": [
            "ChangeLog.md",
            "Agent-shared/skills/changelog-format/SKILL.md",
            "ToDoList.md",
        ],
    },
    "CD": {
        "description": "Continuous Deliverer — Git/anonymization, automated deployment",
        "polling_tasks": [
            "Monitor SOTA updates",
            "Anonymize code when new SOTA is achieved",
            "Execute git commit / push",
            "Report artifact deployment status to PM",
        ],
        "check_files": [
            "sota_project.txt",
            "Agent-shared/directory_pane_map.md",
        ],
    },
    "SOLO": {
        "description": "Solo Agent — Combined PM+SE+PG mode",
        "polling_tasks": [
            "Check the latest ChangeLog.md entry to understand previous results",
            "Select the next optimization task from ToDoList.md",
            "Modify and optimize code, generate new versions",
            "Execute compilation, testing, and job submission end-to-end",
            "Record performance results in ChangeLog.md",
            "Perform SOTA determination and update sota_local.txt if needed",
            "Submit jobs efficiently with budget consumption in mind",
        ],
        "check_files": [
            "ChangeLog.md",
            "ToDoList.md",
            "requirement_definition.md",
        ],
    },
}


def generate_anti_idle_directive(
    role: str,
    agent_id: str = "",
    max_idle_sec: int = 60,
) -> str:
    """Generate the anti-idle section for AGENTS.md.

    Args:
        role: Agent role (PM, SE, PG, CD, SOLO).
        agent_id: Agent identifier (e.g. "PG1.1").
        max_idle_sec: Maximum allowed idle time before the external
            idle detector intervenes.

    Returns:
        Markdown string for the anti-idle directive section.
    """
    role_info = _ROLE_TASKS.get(role, _ROLE_TASKS["PG"])
    tasks = role_info["polling_tasks"]
    check_files = role_info["check_files"]

    task_list = "\n".join(f"{i}. {t}" for i, t in enumerate(tasks, 1))
    file_list = "\n".join(f"- `{f}`" for f in check_files)

    return f"""\
## Anti-Idle Directive (CRITICAL)

**You are a polling agent. You must NEVER idle or stop.**

You are a polling agent ({agent_id or role}). You MUST NOT stop, wait, or
idle under any circumstances. If you have no pending tasks, you MUST
actively search for work by checking the files and tasks listed below.

An external idle detector monitors your activity. If no tool calls are
detected for {max_idle_sec} seconds, you will be forcibly restarted.

### Polling Tasks (by priority)
{task_list}

### Periodic Check Files
{file_list}

### Rules
- Immediately search for the next task after completing one
- Declarations like "done" or "waiting" are prohibited
- When unsure, re-read ChangeLog.md and ToDoList.md
- Communicate with other agents via agent_send.sh
- Repeat steps 1-7 in an infinite loop
"""


def generate_agents_md(
    role: str,
    agent_id: str = "",
    project_name: str = "VibeCodeHPC",
    extra_instructions: str = "",
    max_idle_sec: int = 60,
) -> str:
    """Generate complete AGENTS.md content for a Codex agent.

    Args:
        role: Agent role (PM, SE, PG, CD, SOLO).
        agent_id: Agent identifier.
        project_name: Project name for the header.
        extra_instructions: Additional markdown to append.
        max_idle_sec: Idle timeout for anti-idle directive.

    Returns:
        Complete AGENTS.md content string.
    """
    role_info = _ROLE_TASKS.get(role, _ROLE_TASKS["PG"])

    header = f"""\
# {project_name} — {role} Agent ({agent_id or role})

{role_info["description"]}

"""

    anti_idle = generate_anti_idle_directive(role, agent_id, max_idle_sec)

    communication = f"""\
## Communication

Use `agent_send.sh` for inter-agent communication:
```bash
agent_send.sh <recipient> "[{agent_id or role}] message content"
```

- To PM: `agent_send.sh PM "[{agent_id or role}] report content"`
- To SE: `agent_send.sh SE1 "[{agent_id or role}] request content"`
- Broadcast: `agent_send.sh ALL "[{agent_id or role}] shared information"`
"""

    override_note = """\
## Override

If `AGENTS.override.md` exists, its contents will be appended to this file.
Write project-specific settings in the override file.
"""

    parts = [header, anti_idle, communication, override_note]
    if extra_instructions:
        parts.append(f"\n## Additional Instructions\n\n{extra_instructions}\n")

    return "\n".join(parts)


def write_agents_md(
    target_dir,
    role: str,
    agent_id: str = "",
    **kwargs,
):
    """Write AGENTS.md to a directory.

    Args:
        target_dir: Directory where AGENTS.md will be written.
        role: Agent role.
        agent_id: Agent identifier.
        **kwargs: Forwarded to :func:`generate_agents_md`.

    Returns:
        Path to the written file.
    """
    from pathlib import Path

    target_dir = Path(target_dir)
    target_dir.mkdir(parents=True, exist_ok=True)
    out_path = target_dir / "AGENTS.md"
    content = generate_agents_md(role=role, agent_id=agent_id, **kwargs)
    out_path.write_text(content, encoding="utf-8")
    return out_path
